version: "3.7"

services:
  db:
    image: postgres
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/sql
      - ./backend/db/:/docker-entrypoint-initdb.d

volumes:
  postgres_db:
